microsoft/pxt-maker

libs/gamepad/shims.d.ts, libs/mouse/_locales/mouse-jsdoc-strings.json, libs/mouse/_locales/mouse-strings.json, libs/mouse/enums.d.ts, libs/mouse/pxt.json, libs/mouse/shims.d.ts, package.json, pxtarget.json
Requires the "mouse" branch in pxt-common-packages
=> Support for HID Mouse

libs/core---nrf52832/shims.d.ts, libs/core/shims.d.ts, package.json, sim/dalboard.ts
Support for analogRead simulation.
=> support for photocells

libs/adafruit-circuit-playground-express/device.d.ts, libs/core---nrf52832/shims.d.ts, libs/core/shims.d.ts, libs/music/shims.d.ts, package.json
Sync pin definitions with Adafruit
=> Pin upgrade

sim/dalboard.ts
Support for simulating storage.
=> storage sim support

docs/projects/storage/data-logger.md, docs/projects/storage/write-file.md, libs/adafruit-metro-m0-express/pxt.json, libs/storage/shims.d.ts, pxtarget.json, targetconfig.json
=> move to docker builds

libs/sparkfun-samd21-dev-breakout/config.ts
Hi
Fix pins for sparkfun samd21 dev board
based in https://cdn.sparkfun.com/assets/learn_tutorials/4/5/4/graphicalDatasheet-Dev.pdf
=> Fix pins for sparkfun samd21 dev board

docs/projects/storage.md, docs/projects/storage/data-logger.md, libs/adafruit-circuit-playground-express/pxt.json, libs/adafruit-feather-m0-express/pxt.json, targetconfig.json
Setup Express boards with storage package.
=> Storage docs

libs/adafruit-feather-m0-express/pxt.json, libs/adafruit-itsybitsy-m0-express/pxt.json, libs/adafruit-metro-m0-express/pxt.json, libs/adafruit-trinket-m0/pxt.json
=> adding pixel to trinket

libs/arduino-mkr1300/config.ts, libs/arduino-mkr1300/device.d.ts
* Change pin for A2 and ADC battery in A9
* Fix Pin TX with D14
Thanks
=> Correction pins for MKR1300

sim/visuals/board.ts
All neopixels on CPX now supported.
=> better onboard neopixel support

libs/electroniccats-meow-meow/config.ts
=> fix invert pins I2C for Meow Meow

libs/adafruit-circuit-playground-express/config.ts, libs/sparkfun-samd21-dev-breakout/config.ts, libs/sparkfun-samd21-mini-breakout/config.ts, pxtarget.json
Serial working on PAD0 and PAD2 for SAMD21
=> pickup serial samd21 fix

package.json, pxtarget.json
=> Save as png

libs/adafruit-circuit-playground-express/config.ts, libs/core---nrf52832/shims.d.ts, libs/core---nrf52840/shims.d.ts, libs/core---samd/shims.d.ts, libs/core---samd51/shims.d.ts, libs/core/shims.d.ts, package.json
Refactor I2C, SPI, Serial into TypeScript.
=> I2c device

libs/adafruit-circuit-playground-express/ns.ts, libs/core---nrf52832/shims.d.ts, libs/core---nrf52840/shims.d.ts, libs/core---samd/shims.d.ts, libs/core---samd51/shims.d.ts, libs/core/shims.d.ts, libs/light/shims.d.ts, package.json
Rebuild for https://github.com/Microsoft/pxt-common-packages/pull/693
=> updated shims for neopixel refactoring

docs/projects/analog-io/glow-light.md, docs/projects/analog-io/glowy.md, libs/adafruit-circuit-playground-express/device.d.ts, libs/adafruit-feather-bluefruit-nrf52/device.d.ts, libs/adafruit-feather-m0-express/device.d.ts, libs/adafruit-feather-m4-express/device.d.ts, libs/adafruit-gemma-m0/boardhd.svg, libs/adafruit-gemma-m0/config.ts, libs/adafruit-gemma-m0/device.d.ts, libs/adafruit-metro-m0-express/device.d.ts, libs/adafruit-metro-m4-express/device.d.ts, libs/adafruit-trinket-m0/device.d.ts, libs/arduino-mkr1000/device.d.ts, libs/arduino-mkr1010/device.d.ts, libs/arduino-mkr1300/device.d.ts, libs/arduino-zero/device.d.ts, libs/electroniccats-meow-meow/device.d.ts, libs/redbear-ble-nano/device.d.ts, libs/sparkfun-redboard-turbo/device.d.ts, libs/sparkfun-samd21-dev-breakout/device.d.ts, libs/sparkfun-samd21-mini-breakout/device.d.ts, libs/stitchkit/device.d.ts, libs/teknikio-bluebird/device.d.ts, sim/visuals/board.ts
Allow for glowing LEDs supported in simulator.
=> Support for PWM LED in API/sim

libs/electroniccats-meow-meow/device.d.ts
Hi
we have added more pins available to control servos and buttons
Thanks
=> Add more pins for meowmeow

libs/electroniccats-meow-meow/device.d.ts, libs/electroniccats-meow-meow/ns.ts, libs/electroniccats-meow-meow/pxt.json
=> Add servo to MeowMeow

libs/adafruit-circuit-playground-express/board.json, libs/adafruit-circuit-playground-express/pxt.json, libs/core---nrf52832/platform.cpp, libs/infrared/pxt.json, libs/infrared/shims.d.ts, libs/pulse/pxt.json, package-lock.json, package.json, pxtarget.json, sim/dalboard.ts
Support for IR in CPX. Requires https://github.com/Microsoft/pxt-common-packages/pull/727
=> adding infrared/pulse

libs/adafruit-circuit-playground-express/config.ts, libs/bead-motion/config.ts, package.json, pxtarget.json
Pull in latest pxt + setup accelerometers
=> dynamic detection of accelerometer

.travis.yml, package.json
=> Always install webusb

package.json
this includes the revert of the docs changes
=> pxt v5.24.5

pxtarget.json
=> add docs header name

docs/boards/adafruit-feather-bluefruit-nrf52.md, docs/boards/redbear-ble-nano.md, docs/boards/teknikio-bluebird.md, libs/base---light/shims.d.ts, libs/base/shims.d.ts, libs/microphone/shims.d.ts, package.json, pxtarget.json
Looks like nrf52832 does not build anymore. @mmoskal
=> bump to pxt 5.31.8

theme/blockly-toolbox.less, theme/site/globals/site.variables
=> Set monaco toolbox background and text colors

README.md
@mmoskal if i've missed steps or tricks you have, please add
=> Codal build instructions

docs/boards.md, docs/projects.md, docs/projects/SUMMARY.md, targetconfig.json
=> Board config

libs/core---nrf52/shims.d.ts, libs/core---samd/shims.d.ts, libs/core---samd51/shims.d.ts, libs/core---stm32/shims.d.ts, libs/core/shims.d.ts, libs/nucleo-f411re/board.json, pxtarget.json
Bump pxt + some info in pxtarget
=> External simulators, support for jacdac

libs/arduino-mkr1000/config.ts
=> Wrong PIN for LED defined

docs/projects/SUMMARY.md, package.json, sim/public/sim.manifest, sim/public/simulator.html, sim/tsconfig.json
pxt upgraded to es2017, updating maker.
=> bump to es2017

libs/adafruit-grand-central-m4-express/pxt.json
- added more features
- updated bootloader URL
=> updated adafruit-grand-central-m4 features

targetconfig.json
This should be what you need for bumping pxt-core~
=> add new approvedRepoLib format
